### ISSUE TITLE
Cart dropdown maximum visible products depth

### ISSUE THREAD

**Issue by wildfirecreative** [Stellyclothing/Stelly-New-Website#12]
The cart needs to change to scrolling within the cart when more than 3 products are added as per current cart.

**Comment by Stellyclothing** [comment]
Hi Guys,
Just tested 
The cart dropdown works fine, 

But when I'm trying to go to the checkout 
The dropdown Cart wouldn't go back up. 
It would only go back up when i go back to new arrivals. 

Try to add a few products in your cart , and go to checkout you will understand what I'm talking about
![screen shot 2015-06-15 at 1 08 59 pm](https://cloud.githubusercontent.com/assets/9522928/8152498/0fc42290-1361-11e5-9838-af9605b9a07e.png)

**Comment by wildfirecreative** [comment]
I'm running all my own testing today - got the same thing - should be an
easy fix.



Cheers,

Luke

<http://wildfirecreative.com.au>

**Comment by Stellyclothing** [comment]
Thanks Luke
Josh

**Comment by wildfirecreative** [comment]
The cart also appears to be visible on entering the page - shouldn't show until at least clicked onr a product is added.
![cart hangs on entry](https://cloud.githubusercontent.com/assets/9874220/8153370/6fe9a2f8-1370-11e5-93b5-4527216966f2.png)

**Comment by wildfirecreative** [comment]
This has been fixed
