### ISSUE TITLE
Delay when selected in Shipping Options at checkout

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/Stelly-New-Website#13]
![screen shot 2015-06-15 at 1 10 26 pm](https://cloud.githubusercontent.com/assets/9522928/8152424/32ab93ac-1360-11e5-8f8e-787ce574a3fa.png)

Theres a small delay when i click on Shipping carrier ? 
Im not sure if its right

Please have a look

**Comment by wildfirecreative** [comment]
The delay is probably because the staging server is just slower - I tested
it and don't see any major issue

Cheers,

Luke

<http://wildfirecreative.com.au>
