### ISSUE TITLE
Tax Excluded ? 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/Stelly-New-Website#16]
Hi 
On our current page its tax included 
How come on the new site , its tax excluded ?
Did someone request for this ?

Thanks 
JOsh 
![screen shot 2015-06-16 at 7 14 51 pm](https://cloud.githubusercontent.com/assets/9522928/8179724/e5870c80-145b-11e5-85b0-90c244085e1b.png)
![screen shot 2015-06-16 at 7 14 59 pm](https://cloud.githubusercontent.com/assets/9522928/8179727/e7336b0a-145b-11e5-847f-781101408c72.png)

**Comment by supremesupports** [comment]
We were working on Cart module's setting and then suddenly that message appeared. Its no longer there in cart drop-down. Tax is included with the product price as like live site. Please have a look on cart drop-down and also shopping cart to make sure its fine.

![cart-taxt text](https://cloud.githubusercontent.com/assets/12905649/8181834/3b1793f6-144b-11e5-8e57-7ae2de08e468.png)


Thanks!

**Comment by Stellyclothing** [comment]
THANK YOU 
JOSH
