### ISSUE TITLE
Payment processing message

### ISSUE THREAD

**Issue by wildfirecreative** [Stellyclothing/Stelly-New-Website#23]
Can we please add a message while payments are being processed for customers to not refresh their browsers. This might be causing some of the double payments.

Message:

Your payment is processing. Please do not refresh your browser, or leave this page until the process is complete.

**Comment by Stellyclothing** [comment]
Hey @wildfirecreative @supremesupports 
Should look like this
![avoid double charge](https://cloud.githubusercontent.com/assets/9522928/9840570/c7e364d6-5ad7-11e5-9d45-8977cf36f015.png)

**Comment by Stellyclothing** [comment]
This issue was moved to Stellyclothing/AWS-NEW-WEBSITE-TEST#76
