### ISSUE TITLE
Log in issue with Input Addresses for  Australia Account - No City  - With United States - No States is Allow - Enter Personal address twice 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/Stelly-New-Website#3]
![screen shot 2015-06-04 at 10 54 52 am 2](https://cloud.githubusercontent.com/assets/9522928/8101064/c8cd0d00-1056-11e5-93cc-9b8156290352.png)
Australia Pode charge code is : 3J55

I tried to register
It would let me register fine.
But then we had some issue with the address 

So when i tried to register my address , the country default was USA , it had the City( SUBURB)  Box for entering
I then Changed to Australia and the city section is gone

Below it would ask me to fill me my city 
But theres no where to put my city

**Comment by Stellyclothing** [comment]
Address problem number 2 

This problem is also happening with International 
But only when enter United States as a country - i'm unable to add the correct states in my account

**Comment by supremesupports** [comment]
City field is visible now if you are selecting Australia as country. Also, If you switch country between Australia & USA, States are also changing respectively.

**Comment by Stellyclothing** [comment]
hi 
IM trying to register as a new customer and still having issue with the city 
So as default for united states, i was able to input city 

But as changing to australia suburb/city is not there any more , please see attachment
![screen shot 2015-06-16 at 6 40 50 pm](https://cloud.githubusercontent.com/assets/9522928/8179049/402b35f8-1457-11e5-876c-70cf372a4022.png)
![screen shot 2015-06-16 at 6 40 01 pm](https://cloud.githubusercontent.com/assets/9522928/8179050/407daf86-1457-11e5-900e-30d75a80008b.png)

**Comment by Stellyclothing** [comment]
After i registered with an address 
I selected a product and go to the checkout
The system would ask for my address again 
This time city is there to input

But i shouldn't have to enter my address twice. 
Please have a look 
![screen shot 2015-06-16 at 6 45 41 pm](https://cloud.githubusercontent.com/assets/9522928/8179164/1ca144be-1458-11e5-9583-3196782d5b0c.png)

**Comment by Stellyclothing** [comment]
@wildfirecreative  hey luke, this has not yet been fixed completely

**Comment by wildfirecreative** [comment]
Supreme can you please review this again

**Comment by Stellyclothing** [comment]
This issue was moved to Stellyclothing/AWS-NEW-WEBSITE-TEST#19
