### ISSUE TITLE
Unable to change Category Banner 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/Stelly-New-Website#5]
![products banner not changing on category page](https://cloud.githubusercontent.com/assets/9522928/8103386/63334e18-106b-11e5-966c-c064f768e44b.png)

In all category page , I'm unable to change banner and it would take 3,4 days to change or may be never

**Comment by Stellyclothing** [comment]
![screen shot 2015-06-15 at 1 03 03 pm](https://cloud.githubusercontent.com/assets/9522928/8152301/c13f16fe-135e-11e5-97d8-bd9bc78692f3.png)
![screen shot 2015-06-15 at 1 02 09 pm](https://cloud.githubusercontent.com/assets/9522928/8152306/d22908ee-135e-11e5-884d-3682e31c036b.png)
 Hi I have tried again and it hasn't yet been changed. 

You guys need to try with a different image 
![shipping-banner](https://cloud.githubusercontent.com/assets/9522928/8152312/e13a0cd4-135e-11e5-977f-4203718d41ee.jpg) try this one and see if it changes

**Comment by Stellyclothing** [comment]
@wildfirecreative hi Luke, I have tried and its not working still
Btw you can tag my name in this like @ to notify me when you have answered an issue. 

Thanks 
Josh

**Comment by wildfirecreative** [comment]
I'm checking this with them now. Might just be a caching issue or something

Cheers,

Luke

<http://wildfirecreative.com.au>

**Comment by wildfirecreative** [comment]
Developers have confirmed this is a server cache issue (varnish) not a development issue

**Comment by Stellyclothing** [comment]
Hi @wildfirecreative 
How can we fix this issue ?
I need to activate it for future bug 

Thank You 
Josh
