### ISSUE TITLE
Size is out of stock - Refund Message at Checkout

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/Stelly-New-Website#6]
![red refund message issue](https://cloud.githubusercontent.com/assets/9522928/8103404/978b4508-106b-11e5-8154-9d8a6dde9942.png)
Hi , 
Customer order , and made a purchase , check out and get a message infact it wasn't out of stock 

Please fix. Message needs to be gone

**Comment by supremesupports** [comment]
I've reviewed product settings again on back-end then purchased the same product as mentioned in the screenshot using SecurePay. I don't see any notice/error message. You will only see this notice only if the product is 'Out of Stock'. 

Note that, I purchased last item of this product to make sure if this error is appearing.

**Comment by Stellyclothing** [comment]
Hi 
The goal is to remove this message and it shouldn't be on the front end - Ever - Absolute
Even the product is out of stock , customer shouldn't see this message at all 

Please check and let me know thats what you meant 

Thanks 
Josh

**Comment by Stellyclothing** [comment]
@wildfirecreative Hey luke, please also look into this

**Comment by Stellyclothing** [comment]
@wildfirecreative Hi This needs to be fixed ASAP on our current website 
Lots of refund on our current site 
Please let me know once its completed 

Thanks 
Josh

**Comment by supremesupports** [comment]
Hi,
We realized that this part needs to be done on Staging site ONLY which is already done couple of weeks ago. We are sorry to misunderstood and we already started working on this from today.

Thanks.

**Comment by supremesupports** [comment]
Hi,
I did some work on this issue & hopefully no further notification will be shown to its customer related to product quantity.

Can you please check back and let us know if this issue is resolved.

Thank you.

**Comment by Stellyclothing** [comment]
Hey guys, this has been fixed on our current website, But has it been fixed on our new website ?  
@wildfirecreative @supremesupports 

Thanks
Josh
